const activity = {
  image: {
    Basketball: require('../../Assets/Images/Activities/basketball.png'),
    Biking: require('../../Assets/Images/Activities/biking.png'),
    Cheer: require('../../Assets/Images/Activities/cheer.png'),
    Football: require('../../Assets/Images/Activities/football.png'),
    Golf: require('../../Assets/Images/Activities/golf.png'),
    Gymnastics: require('../../Assets/Images/Activities/gymnastics.png'),
    Hockey: require('../../Assets/Images/Activities/hockey.png'),
    Lacrosse: require('../../Assets/Images/Activities/lacrosse.png'),
    Running: require('../../Assets/Images/Activities/running.png'),
    Scootering: require('../../Assets/Images/Activities/scootering.png'),
    Skateboarding: require('../../Assets/Images/Activities/skateboarding.png'),
    Skiing: require('../../Assets/Images/Activities/skiing.png'),
    Soccer: require('../../Assets/Images/Activities/soccer.png'),
    Surfing: require('../../Assets/Images/Activities/surfing.png'),
    Swimming: require('../../Assets/Images/Activities/swimming.png'),
    Tennis: require('../../Assets/Images/Activities/tennis.png'),
    Volleyball: require('../../Assets/Images/Activities/volleyball.png'),
    Weightlifting: require('../../Assets/Images/Activities/weightlifting.png'),
    Yoga: require('../../Assets/Images/Activities/yoga.png'),
    Dance: require('../../Assets/Images/Activities/dance.png'),
    Hiking: require('../../Assets/Images/Activities/hike.png'),
    Walking: require('../../Assets/Images/Activities/walk.png'),
    MartialArts: require('../../Assets/Images/Activities/martialarts.png'),
    Happy: require('../../Assets/Images/Moods/happy.png'),
    Loved: require('../../Assets/Images/Moods/loved.png'),
    Silly: require('../../Assets/Images/Moods/silly.png'),
    Confident: require('../../Assets/Images/Moods/confident.png'),
    Excited: require('../../Assets/Images/Moods/excited.png'),
    Relaxed: require('../../Assets/Images/Moods/relaxed.png'),
    Confused: require('../../Assets/Images/Moods/confused.png'),
    Bored: require('../../Assets/Images/Moods/bored.png'),
    Tired: require('../../Assets/Images/Moods/tired.png'),
    Frustrated: require('../../Assets/Images/Moods/frustrated.png'),
    Stressed: require('../../Assets/Images/Moods/stressed.png'),
    Nervous: require('../../Assets/Images/Moods/nervous.png'),
    Worried: require('../../Assets/Images/Moods/worried.png'),
    Lonely: require('../../Assets/Images/Moods/lonely.png'),
    Hurt: require('../../Assets/Images/Moods/hurt.png'),
    Sick: require('../../Assets/Images/Moods/sick.png'),
    Mad: require('../../Assets/Images/Moods/angry.png'),
    Sad: require('../../Assets/Images/Moods/sad.png'),
    Depressed: require('../../Assets/Images/Moods/depressed.png'),
    Overwhelmed: require('../../Assets/Images/Moods/overwhelmed.png'),
    Hopeful: require('../../Assets/Images/Moods/hopeful.png'),
    Grateful: require('../../Assets/Images/Moods/grateful.png'),
    Disappointed: require('../../Assets/Images/Moods/disappointed.png'),
    Annoyed: require('../../Assets/Images/Moods/annoyed.png'),
    Goofy: require('../../Assets/Images/Moods/silly.png'),
    Scared: require('../../Assets/Images/Moods/afraid.png'),
  }
};

export default activity;
