/**
 * The initial values for the redux state.
 */
export const INITIAL_STATE = {
  user: {},
  mood: {},
  mindfulness: {},
  video: {},
  sleep: {},
  overall: {},
  sleeps: {},
  sleepWeek: {},
  activity: {},
  activities: {},
  moods: {},
  mindfulnesses: {},
  moodScores: {},
  activityScores: {},
  moodData: [],
  moodIcons: [],
  moodEntries: [],
  moodHours: [],
  moodWeekData: [],
  moodWeekIcons: [],
  moodWeekHours: [],
  moodWeekDays: [],
  mindfulnessWeekData: [],
  mindfulnessWeekIcons: [],
  mindfulnessWeekHours: [],
  mindfulnessWeekDays: [],
  moodMonthStats: [],
  sleepMonthStats: [],
  activityMonthStats: [],
  activityWeekData: [],
  activityWeekIcons: [],
  activityWeekHours: [],
  activityWeekDays: [],
  sleepScores: {},
  balanceScores: {},
  dataIsLoading: false,
  userErrorMessage: null,
  userIsLoading: false,
  isFetching: false,
  isMonthFetching: false,
  error: null,
  sleepDays: [],
  sleepData: [],
  mindfulnessData: [],
  activityHours: [],
  activityData: [],
  activityIcons: [],
  triangle: { labels: ['Activity', 'Mood', 'Sleep'], data: [0.0, 0.0, 0.0] },
  average: 0,
  commitsData: [],

  // isAuthenticated = false,
  // isConnecting = false,
}
